name: Update Stock Data

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "0 1 * * *" # Runs daily at 01:00 UTC

jobs:
  update-stock-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # Step 4: Run the Python script
      - name: Generate stock_data.json
        run: |
          python preprocess_data.py

      # Step 5: Commit and push changes
      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update stock_data.json [skip ci]"
          file_pattern: stock_data.json
          branch: main
